### ISSUE TITLE
application.properties

### ISSUE THREAD

**Issue by J-minkuk** [ldcpaul/Spring_Boot#1]
이 파일에는 개인 정보 설정 같은게 있기 때문에
.gitignore 하는게 좋아

이미 올라간거 지워봤자 commit log에 남음
어차피 지금은 로컬이라 크게 상관없는데
나중에 AWS 같은거로 할 때 조심하길

**Comment by O-O-wl** [comment]
아 비공개 해야하는군여 감사합니다
